// packages/react/src/components/ui/FontPicker.tsx
/**
 * Font Picker Component (Radix UI)
 *
 * A dropdown selector for choosing font families using Radix Select.
 */

import * as React from 'react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectGroup,
  SelectLabel,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
} from './Select';
import { cn } from '../../lib/utils';
import { useTranslation } from '../../i18n';
import { getPrimaryFontFamily } from './fontPickerValue';
import { excludeFontsByName } from '@xcrong/docx-editor-core/utils';

// ============================================================================
// TYPES
// ============================================================================

export type { FontOption } from '@xcrong/docx-editor-core/utils/fontOptions';
import type { FontOption } from '@xcrong/docx-editor-core/utils/fontOptions';

export interface FontPickerProps {
  value?: string;
  onChange?: (fontFamily: string) => void;
  fonts?: FontOption[];
  /**
   * Fonts the loaded document references that the browser can render. Shown in
   * a "Document fonts" group above the built-in list, deduped against `fonts`.
   */
  documentFonts?: readonly FontOption[];
  disabled?: boolean;
  className?: string;
  placeholder?: string;
  width?: number | string;
  showPreview?: boolean;
}

// ============================================================================
// DEFAULT FONTS
// ============================================================================

const DEFAULT_FONTS: FontOption[] = [
  // Sans-serif
  { name: 'Arial', fontFamily: 'Arial, Helvetica, sans-serif', category: 'sans-serif' },
  { name: 'Calibri', fontFamily: '"Calibri", Arial, sans-serif', category: 'sans-serif' },
  { name: 'Helvetica', fontFamily: 'Helvetica, Arial, sans-serif', category: 'sans-serif' },
  { name: 'Verdana', fontFamily: 'Verdana, Geneva, sans-serif', category: 'sans-serif' },
  { name: 'Open Sans', fontFamily: '"Open Sans", sans-serif', category: 'sans-serif' },
  { name: 'Roboto', fontFamily: 'Roboto, sans-serif', category: 'sans-serif' },
  // Serif
  { name: 'Times New Roman', fontFamily: '"Times New Roman", Times, serif', category: 'serif' },
  { name: 'Georgia', fontFamily: 'Georgia, serif', category: 'serif' },
  { name: 'Cambria', fontFamily: 'Cambria, Georgia, serif', category: 'serif' },
  { name: 'Garamond', fontFamily: 'Garamond, serif', category: 'serif' },
  // Monospace
  { name: 'Courier New', fontFamily: '"Courier New", Courier, monospace', category: 'monospace' },
  { name: 'Consolas', fontFamily: 'Consolas, monospace', category: 'monospace' },
];

// ============================================================================
// COMPONENT
// ============================================================================

export function FontPicker({
  value,
  onChange,
  fonts = DEFAULT_FONTS,
  documentFonts,
  disabled = false,
  className,
  placeholder = 'Arial',
  width = 120,
  showPreview = true,
}: FontPickerProps) {
  const { t } = useTranslation();

  // Document fonts shown above the built-in list, minus any the built-in list
  // already covers (case-insensitive) so a font never appears twice.
  const docFonts = React.useMemo(
    () =>
      excludeFontsByName(
        documentFonts,
        fonts.map((f) => f.name)
      ),
    [documentFonts, fonts]
  );

  // Lookups (display + change) span both the document group and the main list.
  const lookupFonts = React.useMemo(() => [...docFonts, ...fonts], [docFonts, fonts]);

  // Find current font name for display
  const displayValue = React.useMemo(() => {
    if (!value) return placeholder;
    const font = lookupFonts.find(
      (f) =>
        f.fontFamily === value ||
        f.name.toLowerCase() === value.toLowerCase() ||
        getPrimaryFontFamily(f.fontFamily).toLowerCase() === value.toLowerCase()
    );
    return font?.name || value;
  }, [value, lookupFonts, placeholder]);

  const handleValueChange = React.useCallback(
    (newValue: string) => {
      const font = lookupFonts.find((f) => f.name === newValue);
      if (font) {
        onChange?.(getPrimaryFontFamily(font.fontFamily) || font.name);
      }
    },
    [onChange, lookupFonts]
  );

  // Group fonts by category
  const groupedFonts = React.useMemo(() => {
    const groups: Record<string, FontOption[]> = {
      'sans-serif': [],
      serif: [],
      monospace: [],
      other: [],
    };
    fonts.forEach((font) => {
      const category = font.category || 'other';
      groups[category].push(font);
    });
    return groups;
  }, [fonts]);

  return (
    <Select value={displayValue} onValueChange={handleValueChange} disabled={disabled}>
      <SelectTrigger
        className={cn('h-8 text-sm', className)}
        style={{ minWidth: typeof width === 'number' ? `${width}px` : width }}
        aria-label={t('font.selectAriaLabel')}
      >
        <SelectValue placeholder={placeholder}>{displayValue}</SelectValue>
      </SelectTrigger>
      <SelectContent className="max-h-[300px]">
        {docFonts.length > 0 && (
          <>
            <SelectGroup>
              <SelectLabel>{t('font.documentFonts')}</SelectLabel>
              {docFonts.map((font) => (
                <SelectItem
                  key={`doc-${font.name}`}
                  value={font.name}
                  style={showPreview ? { fontFamily: font.fontFamily } : undefined}
                >
                  {font.name}
                </SelectItem>
              ))}
            </SelectGroup>
            <SelectSeparator />
          </>
        )}
        {groupedFonts['sans-serif'].length > 0 && (
          <SelectGroup>
            <SelectLabel>{t('font.sansSerif')}</SelectLabel>
            {groupedFonts['sans-serif'].map((font) => (
              <SelectItem
                key={font.name}
                value={font.name}
                style={showPreview ? { fontFamily: font.fontFamily } : undefined}
              >
                {font.name}
              </SelectItem>
            ))}
          </SelectGroup>
        )}
        {groupedFonts['serif'].length > 0 && (
          <>
            <SelectSeparator />
            <SelectGroup>
              <SelectLabel>{t('font.serif')}</SelectLabel>
              {groupedFonts['serif'].map((font) => (
                <SelectItem
                  key={font.name}
                  value={font.name}
                  style={showPreview ? { fontFamily: font.fontFamily } : undefined}
                >
                  {font.name}
                </SelectItem>
              ))}
            </SelectGroup>
          </>
        )}
        {groupedFonts['monospace'].length > 0 && (
          <>
            <SelectSeparator />
            <SelectGroup>
              <SelectLabel>{t('font.monospace')}</SelectLabel>
              {groupedFonts['monospace'].map((font) => (
                <SelectItem
                  key={font.name}
                  value={font.name}
                  style={showPreview ? { fontFamily: font.fontFamily } : undefined}
                >
                  {font.name}
                </SelectItem>
              ))}
            </SelectGroup>
          </>
        )}
        {groupedFonts['other'].length > 0 && (
          <>
            <SelectSeparator />
            <SelectGroup>
              {groupedFonts['other'].map((font) => (
                <SelectItem
                  key={font.name}
                  value={font.name}
                  style={showPreview ? { fontFamily: font.fontFamily } : undefined}
                >
                  {font.name}
                </SelectItem>
              ))}
            </SelectGroup>
          </>
        )}
      </SelectContent>
    </Select>
  );
}

// packages/vue/src/components/ui/FontPicker.vue
<!--
  Vue port of packages/react/src/components/ui/FontPicker.tsx —
  font family picker grouped by category. Shares the FontOption
  type with React via @xcrong/docx-editor-core/utils/fontOptions.
  Native <select> with <optgroup> rather than radix-vue.
-->
<template>
  <select
    class="docx-font-picker"
    :value="displayValue"
    :disabled="disabled"
    :class="className"
    aria-label="Font family"
    @change="onChange"
  >
    <optgroup v-if="groups['sans-serif'].length" label="Sans-serif">
      <option
        v-for="f in groups['sans-serif']"
        :key="f.name"
        :value="f.name"
        :style="showPreview ? { fontFamily: f.fontFamily } : undefined"
      >{{ f.name }}</option>
    </optgroup>
    <optgroup v-if="groups['serif'].length" label="Serif">
      <option
        v-for="f in groups['serif']"
        :key="f.name"
        :value="f.name"
        :style="showPreview ? { fontFamily: f.fontFamily } : undefined"
      >{{ f.name }}</option>
    </optgroup>
    <optgroup v-if="groups['monospace'].length" label="Monospace">
      <option
        v-for="f in groups['monospace']"
        :key="f.name"
        :value="f.name"
        :style="showPreview ? { fontFamily: f.fontFamily } : undefined"
      >{{ f.name }}</option>
    </optgroup>
    <optgroup v-if="groups['other'].length" label="Other">
      <option
        v-for="f in groups['other']"
        :key="f.name"
        :value="f.name"
        :style="showPreview ? { fontFamily: f.fontFamily } : undefined"
      >{{ f.name }}</option>
    </optgroup>
  </select>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { FontOption } from '@xcrong/docx-editor-core/utils/fontOptions';
import { getPrimaryFontFamily } from './fontPickerValue';

export type { FontOption };

const props = withDefaults(
  defineProps<{
    value?: string;
    fonts?: FontOption[];
    disabled?: boolean;
    className?: string;
    placeholder?: string;
    showPreview?: boolean;
  }>(),
  { disabled: false, placeholder: 'Font', showPreview: true }
);

const emit = defineEmits<{
  (e: 'change', fontFamily: string): void;
}>();

const DEFAULT_FONTS: FontOption[] = [
  { name: 'Arial', fontFamily: 'Arial, Helvetica, sans-serif', category: 'sans-serif' },
  { name: 'Calibri', fontFamily: '"Calibri", Arial, sans-serif', category: 'sans-serif' },
  { name: 'Helvetica', fontFamily: 'Helvetica, Arial, sans-serif', category: 'sans-serif' },
  { name: 'Verdana', fontFamily: 'Verdana, Geneva, sans-serif', category: 'sans-serif' },
  { name: 'Open Sans', fontFamily: '"Open Sans", sans-serif', category: 'sans-serif' },
  { name: 'Roboto', fontFamily: 'Roboto, sans-serif', category: 'sans-serif' },
  { name: 'Times New Roman', fontFamily: '"Times New Roman", Times, serif', category: 'serif' },
  { name: 'Georgia', fontFamily: 'Georgia, serif', category: 'serif' },
  { name: 'Cambria', fontFamily: 'Cambria, Georgia, serif', category: 'serif' },
  { name: 'Garamond', fontFamily: 'Garamond, serif', category: 'serif' },
  { name: 'Courier New', fontFamily: '"Courier New", monospace', category: 'monospace' },
  { name: 'Consolas', fontFamily: 'Consolas, monospace', category: 'monospace' },
];

const resolvedFonts = computed(() => props.fonts ?? DEFAULT_FONTS);
const groups = computed(() => {
  const out: Record<'sans-serif' | 'serif' | 'monospace' | 'other', FontOption[]> = {
    'sans-serif': [],
    serif: [],
    monospace: [],
    other: [],
  };
  for (const f of resolvedFonts.value) out[f.category ?? 'other'].push(f);
  return out;
});

const displayValue = computed(() => {
  if (!props.value) return props.placeholder;
  const m = resolvedFonts.value.find(
    (f) =>
      f.fontFamily === props.value ||
      f.name.toLowerCase() === props.value!.toLowerCase() ||
      getPrimaryFontFamily(f.fontFamily).toLowerCase() === props.value!.toLowerCase()
  );
  return m?.name ?? props.value;
});

function onChange(e: Event) {
  const name = (e.target as HTMLSelectElement).value;
  const font = resolvedFonts.value.find((f) => f.name === name);
  emit('change', font ? getPrimaryFontFamily(font.fontFamily) || font.name : name);
}
</script>

<style scoped>
.docx-font-picker {
  height: 28px;
  font-size: 13px;
  min-width: 100px;
  border: 1px solid var(--doc-border-dark);
  border-radius: 4px;
  padding: 0 6px;
  background: var(--doc-surface);
  cursor: pointer;
}
.docx-font-picker:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}
</style>
