// packages/react/src/components/ui/TableBorderColorPicker.tsx
/**
 * TableBorderColorPicker - Wrapper around ColorPicker for table border colors.
 *
 * Translates ColorPicker's ColorValue output to the TableAction format
 * expected by the toolbar's table action handler.
 */

import { useCallback } from 'react';
import type { ColorValue } from '@xcrong/docx-editor-core/types/document';
import type { Theme } from '@xcrong/docx-editor-core/types/document';
import type { TableAction } from './TableToolbar';
import { ColorPicker } from './ColorPicker';
import { useTranslation } from '../../i18n';

export interface TableBorderColorPickerProps {
  onAction: (action: TableAction) => void;
  disabled?: boolean;
  theme?: Theme | null;
  /** Current border color (RGB hex without #) */
  value?: string;
}

export function TableBorderColorPicker({
  onAction,
  disabled = false,
  theme,
  value,
}: TableBorderColorPickerProps) {
  const { t } = useTranslation();
  const handleChange = useCallback(
    (color: ColorValue | string) => {
      if (typeof color === 'string') {
        onAction({ type: 'borderColor', color: color.replace(/^#/, '') });
      } else if (color.rgb) {
        onAction({ type: 'borderColor', color: color.rgb.replace(/^#/, '') });
      } else if (color.auto) {
        onAction({ type: 'borderColor', color: '000000' });
      }
    },
    [onAction]
  );

  return (
    <ColorPicker
      mode="border"
      value={value}
      onChange={handleChange}
      theme={theme}
      disabled={disabled}
      title={t('table.borderColor')}
    />
  );
}

export default TableBorderColorPicker;

// packages/vue/src/components/ui/TableBorderColorPicker.vue
<!--
  Vue port of packages/react/src/components/ui/TableBorderColorPicker.tsx —
  a thin wrapper around the advanced <ColorPicker> (mode="border") that
  translates its ColorValue output to the hex string the table toolbar
  expects. Same theme-color matrix as the text/highlight pickers.
-->
<template>
  <ColorPicker
    mode="border"
    :value="value"
    :theme="theme ?? null"
    :disabled="disabled"
    :title="t('table.borderColor')"
    @change="onChange"
  />
</template>

<script setup lang="ts">
import type { ColorValue, Theme } from '@xcrong/docx-editor-core/types/document';
import ColorPicker from './ColorPicker.vue';
import { useTranslation } from '../../i18n';

defineProps<{
  disabled?: boolean;
  theme?: Theme | null;
  /** Current border color (RGB hex without #). */
  value?: string;
}>();

const emit = defineEmits<{
  (e: 'change', hex: string): void;
}>();

const { t } = useTranslation();

function onChange(color: ColorValue | string) {
  if (typeof color === 'string') emit('change', color.replace(/^#/, ''));
  else if (color.rgb) emit('change', color.rgb.replace(/^#/, ''));
  else if (color.auto) emit('change', '000000');
}
</script>
