// packages/vue/src/components/ui/TableCellFillPicker.vue
<!--
  Vue port of packages/react/src/components/ui/TableCellFillPicker.tsx —
  a thin wrapper around the advanced <ColorPicker> (mode="highlight",
  fill icon + "No fill" label) that translates its output to the hex
  string the table toolbar expects (empty string = clear fill).
-->
<template>
  <ColorPicker
    mode="highlight"
    :value="value"
    :theme="theme ?? null"
    :disabled="disabled"
    :title="t('table.cellFillColor')"
    icon="format_color_fill"
    :auto-label="t('colorPicker.noColor')"
    @change="onChange"
  />
</template>

<script setup lang="ts">
import type { ColorValue, Theme } from '@xcrong/docx-editor-core/types/document';
import ColorPicker from './ColorPicker.vue';
import { useTranslation } from '../../i18n';

defineProps<{
  disabled?: boolean;
  theme?: Theme | null;
  /** Current fill color (RGB hex without #). */
  value?: string;
}>();

const emit = defineEmits<{
  (e: 'change', hex: string): void;
}>();

const { t } = useTranslation();

function onChange(color: ColorValue | string) {
  // Highlight mode emits a string: 'none' (clear fill) or a hex.
  if (typeof color !== 'string') return;
  emit('change', color === 'none' ? '' : color.replace(/^#/, ''));
}
</script>

// packages/react/src/components/ui/TableCellFillPicker.tsx
/**
 * TableCellFillPicker - Wrapper around ColorPicker for table cell fill/shading.
 *
 * Translates ColorPicker's output to the TableAction format
 * expected by the toolbar's table action handler.
 */

import { useCallback } from 'react';
import type { ColorValue, Theme } from '@xcrong/docx-editor-core/types/document';
import type { TableAction } from './TableToolbar';
import { ColorPicker } from './ColorPicker';
import { useTranslation } from '../../i18n';

export interface TableCellFillPickerProps {
  onAction: (action: TableAction) => void;
  disabled?: boolean;
  theme?: Theme | null;
  /** Current fill color (RGB hex without #) */
  value?: string;
}

export function TableCellFillPicker({
  onAction,
  disabled = false,
  theme,
  value,
}: TableCellFillPickerProps) {
  const { t } = useTranslation();
  const handleChange = useCallback(
    (color: ColorValue | string) => {
      // highlight mode emits hex strings or 'none'
      if (typeof color === 'string') {
        if (color === 'none') {
          onAction({ type: 'cellFillColor', color: null });
        } else {
          onAction({ type: 'cellFillColor', color: color.replace(/^#/, '') });
        }
      }
    },
    [onAction]
  );

  return (
    <ColorPicker
      mode="highlight"
      value={value}
      onChange={handleChange}
      theme={theme}
      disabled={disabled}
      title={t('table.cellFillColor')}
      icon="format_color_fill"
      autoLabel={t('colorPicker.noColor')}
    />
  );
}

export default TableCellFillPicker;
