// packages/react/src/components/DocumentOutline.tsx
import React, { useEffect, useState } from 'react';
import type { HeadingInfo } from '@xcrong/docx-editor-core/utils';
import { MaterialSymbol } from './ui/Icons';
import { useTranslation } from '../i18n';

/** @deprecated Use HeadingInfo from utils/headingCollector instead */
export type OutlineHeading = HeadingInfo;

// Outline panel geometry (px). Only the *_RESERVED_SPACE values leak out —
// the editor uses them to size the layout so the centered page never sits
// under the panel or the toggle button. The anchor matches the collapsed
// toggle's left offset so the back arrow lands where the toggle was (the
// panel reads as the toggle expanding in place).
export const OUTLINE_LEFT_OFFSET = 12;
const OUTLINE_WIDTH = 240;
const OUTLINE_PAGE_GAP = 16;
// Matches PagedEditor's VIEWPORT_PADDING_TOP so the panel header lines up
// with the page's top edge.
const OUTLINE_TOP_PADDING = 24;
export const OUTLINE_RESERVED_SPACE = OUTLINE_LEFT_OFFSET + OUTLINE_WIDTH + OUTLINE_PAGE_GAP;

// Toggle-button geometry (when the panel is collapsed): button anchor + disc
// box (36px) + gap before the page. The anchor sits in the left gutter roughly
// under the title-bar logo (Google-Docs placement), not pushed toward the page.
export const OUTLINE_BUTTON_LEFT_OFFSET = 12;
const OUTLINE_BUTTON_BOX = 36;
export const OUTLINE_BUTTON_RESERVED_SPACE =
  OUTLINE_BUTTON_LEFT_OFFSET + OUTLINE_BUTTON_BOX + OUTLINE_PAGE_GAP;

interface DocumentOutlineProps {
  headings: HeadingInfo[];
  onHeadingClick: (pmPos: number) => void;
  onClose: () => void;
  topOffset?: number;
  /** Horizontal scroll offset of the editor — outline slides left with the doc. */
  scrollLeft?: number;
  /**
   * Left anchor (px) from the editor area's left edge. Defaults to
   * OUTLINE_LEFT_OFFSET; the host bumps it past the vertical ruler when one
   * is shown so the panel doesn't render on top of it.
   */
  leftOffset?: number;
}

export const DocumentOutline = React.memo(function DocumentOutline({
  headings,
  onHeadingClick,
  onClose,
  topOffset = 0,
  scrollLeft = 0,
  leftOffset = OUTLINE_LEFT_OFFSET,
}: DocumentOutlineProps) {
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);

  // Indent relative to the shallowest heading present, not the absolute level.
  // A doc whose top sections are Heading 2 (level 1, e.g. a memo with no H1)
  // should still left-align them at the base instead of carrying a phantom
  // first-level indent.
  const minLevel = headings.length ? Math.min(...headings.map((h) => h.level)) : 0;

  useEffect(() => {
    // Trigger slide-in on next frame
    requestAnimationFrame(() => setOpen(true));
  }, []);

  return (
    <nav
      className="docx-outline-nav"
      role="navigation"
      aria-label={t('documentOutline.ariaLabel')}
      style={{
        position: 'absolute',
        top: topOffset,
        // Anchor to leftOffset, then slide left by the editor's horizontal
        // scroll so the panel tracks the doc instead of staying pinned to
        // the viewport.
        left: leftOffset - scrollLeft,
        bottom: 0,
        width: OUTLINE_WIDTH,
        paddingTop: OUTLINE_TOP_PADDING,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        fontFamily: "'Google Sans', Roboto, Arial, sans-serif",
        zIndex: 40,
        // Slide-in animation — translate fully off-screen left of its anchor.
        // Only `transform` transitions; horizontal-scroll tracking via `left`
        // is intentionally untransitioned so the panel keeps up with the doc.
        transform: open ? 'translateX(0)' : `translateX(-${leftOffset + OUTLINE_WIDTH}px)`,
        transition: 'transform 0.15s ease-out',
      }}
      onMouseDown={(e) => e.stopPropagation()}
    >
      {/* Header — back arrow + title. No left padding so the back arrow sits
          at the nav anchor (= the collapsed toggle's position). */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          padding: '16px 16px 12px 0',
        }}
      >
        <button
          onClick={onClose}
          aria-label={t('documentOutline.closeAriaLabel')}
          style={{
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            padding: 4,
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            color: 'var(--doc-text-muted)',
          }}
          title={t('documentOutline.closeTitle')}
        >
          <MaterialSymbol name="arrow_back" size={20} />
        </button>
        <span
          style={{
            fontWeight: 400,
            fontSize: 14,
            color: 'var(--doc-text)',
            letterSpacing: '0.01em',
          }}
        >
          {t('documentOutline.title')}
        </span>
      </div>

      {/* Heading list. Small left padding so items sit close to the left
          gutter (under the back arrow), not in a wide indent band. Per-level
          indent (level is 0-based: Heading 1 = 0) nests sub-headings. */}
      <div style={{ overflowY: 'auto', flex: 1, paddingLeft: 4 }}>
        {headings.length === 0 ? (
          <div
            style={{
              padding: '8px 16px',
              color: 'var(--doc-text-subtle)',
              fontSize: 13,
              lineHeight: '20px',
            }}
          >
            {t('documentOutline.noHeadings')}
          </div>
        ) : (
          headings.map((heading, index) => (
            <div
              key={`${heading.pmPos}-${index}`}
              style={{
                marginLeft: (heading.level - minLevel) * 16,
              }}
            >
              <button
                className="docx-outline-heading-btn"
                onClick={() => onHeadingClick(heading.pmPos)}
                style={{
                  display: 'block',
                  width: '100%',
                  textAlign: 'left',
                  background: 'none',
                  border: 'none',
                  cursor: 'pointer',
                  padding: '5px 8px',
                  fontSize: 13,
                  fontWeight: 400,
                  color: 'var(--doc-text)',
                  lineHeight: '18px',
                  whiteSpace: 'nowrap',
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  borderRadius: 0,
                  letterSpacing: '0.01em',
                }}
                title={heading.text}
              >
                {heading.text}
              </button>
            </div>
          ))
        )}
      </div>
    </nav>
  );
});

// packages/vue/src/components/DocumentOutline.vue
<!--
  Vue document outline panel — mirrors React's `<DocumentOutline>`
  (DocumentOutline.tsx). Slides in from the left edge of the viewport,
  overlays the editor without consuming layout space, uses the same
  240px width / arrow_back icon / title text / empty-state copy as
  React so the two adapters look identical.
-->
<template>
  <nav
    v-if="isOpen"
    class="doc-outline"
    :style="{ left: leftOffset + 'px', top: topPx + 'px' }"
    role="navigation"
    aria-label="Document outline"
    @mousedown.stop
  >
    <div class="doc-outline__header">
      <button
        class="doc-outline__back"
        :title="'Close outline'"
        :aria-label="'Close outline'"
        @click="$emit('close')"
      >
        <MaterialSymbol name="arrow_back" :size="20" />
      </button>
      <span class="doc-outline__title">Document Outline</span>
    </div>
    <div class="doc-outline__body">
      <div v-if="headings.length === 0" class="doc-outline__empty">No headings found</div>
      <button
        v-for="(h, i) in headings"
        :key="i"
        class="doc-outline__item"
        :style="{ paddingLeft: 8 + (h.level - minLevel) * 16 + 'px' }"
        @mousedown.prevent="$emit('navigate', h.pmPos)"
      >
        {{ h.text || '(untitled)' }}
      </button>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { HeadingInfo } from '@xcrong/docx-editor-core/utils/headingCollector';
import MaterialSymbol from './ui/MaterialSymbol.vue';

const props = withDefaults(
  defineProps<{
    isOpen: boolean;
    headings: HeadingInfo[];
    /** Left anchor (px); host bumps it past the vertical ruler when shown. */
    leftOffset?: number;
    /** Top anchor (px); host bumps it past the sticky ruler row when shown. */
    topPx?: number;
  }>(),
  { leftOffset: 12, topPx: 24 }
);

// Indent relative to the shallowest heading present (mirrors React) so a doc
// whose top sections are Heading 2 doesn't carry a phantom first-level indent.
const minLevel = computed(() =>
  props.headings.length ? Math.min(...props.headings.map((h) => h.level)) : 0
);

defineEmits<{
  (e: 'close'): void;
  (e: 'navigate', pmPos: number): void;
}>();
</script>

<style scoped>
/* Matches React DocumentOutline.tsx: position: absolute against the
   editor host, anchored 12px from the left (= the collapsed toggle's
   offset so the back arrow lands where the toggle was), 240px wide,
   full height. The wrapping `__editor-area` has position: relative so
   this lands on top of the page area without consuming flex space. The
   slide-in uses transform so it doesn't trigger layout. */
.doc-outline {
  position: absolute;
  /* `left` and `top` are set inline by the host: `left` via the leftOffset prop
     (page left anchor, bumped when the vertical ruler is shown), `top` at the
     page top edge, bumped past the sticky ruler row when one is shown. */
  bottom: 0;
  width: 240px;
  display: flex;
  flex-direction: column;
  font-family: 'Google Sans', Roboto, Arial, sans-serif;
  z-index: 40;
  animation: docOutlineIn 0.15s ease-out;
}
@keyframes docOutlineIn {
  /* Large enough to fully hide the 240px panel at any left anchor (12 or,
     when the vertical ruler is shown, 32 → right edge 272). */
  from {
    transform: translateX(-300px);
  }
  to {
    transform: translateX(0);
  }
}
/* No left padding so the back arrow sits at the nav anchor (= the
   collapsed toggle's position). */
.doc-outline__header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 16px 16px 12px 0;
}
.doc-outline__back {
  background: none;
  border: none;
  cursor: pointer;
  padding: 4px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  color: var(--doc-text-muted);
}
.doc-outline__back:hover {
  background: var(--doc-shadow-subtle);
}
.doc-outline__title {
  font-weight: 400;
  font-size: 14px;
  color: var(--doc-text);
  letter-spacing: 0.01em;
}
.doc-outline__body {
  flex: 1;
  overflow-y: auto;
  padding-left: 4px;
}
.doc-outline__empty {
  padding: 8px 16px;
  color: var(--doc-text-subtle);
  font-size: 13px;
  line-height: 20px;
}
.doc-outline__item {
  display: block;
  width: 100%;
  text-align: left;
  padding: 6px 12px;
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 13px;
  color: var(--doc-text-muted);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  border-radius: 4px;
}
.doc-outline__item:hover {
  background: var(--doc-shadow-subtle);
}
</style>
