// examples/nuxt/app.vue
<template>
  <div class="app">
    <header class="header">
      <h1 class="title">docx-editor · Nuxt module</h1>
      <span v-if="status" class="status">{{ status }}</span>
      <label class="btn btn-primary">
        <input type="file" accept=".docx" class="file-input" @change="onFileSelect" />
        Open DOCX
      </label>
      <button class="btn" @click="onNew">New</button>
    </header>
    <main class="main">
      <!--
        <DocxEditor> is auto-imported and registered client-only by
        @xcrong/nuxt-docx-editor — no import or <ClientOnly> wrapper needed.
      -->
      <DocxEditor
        :document="documentBuffer ? undefined : currentDocument"
        :document-buffer="documentBuffer"
        :show-toolbar="true"
        @error="onError"
      />
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { createEmptyDocument, type Document } from '@xcrong/docx-editor-core';

const documentBuffer = ref<ArrayBuffer | undefined>(undefined);
const currentDocument = ref<Document | null>(null);
const status = ref('');

// Runs in the browser only — the editor never renders during SSR.
onMounted(async () => {
  try {
    const res = await fetch('/sample.docx');
    documentBuffer.value = await res.arrayBuffer();
  } catch {
    currentDocument.value = createEmptyDocument();
  }
});

async function onFileSelect(event: Event) {
  const file = (event.target as HTMLInputElement).files?.[0];
  if (!file) return;
  status.value = 'Loading…';
  try {
    const buffer = await file.arrayBuffer();
    currentDocument.value = null;
    documentBuffer.value = buffer;
    status.value = '';
  } catch {
    status.value = 'Error loading file';
  }
}

function onNew() {
  documentBuffer.value = undefined;
  currentDocument.value = createEmptyDocument();
  status.value = '';
}

function onError(error: Error) {
  console.error('Editor error:', error);
  status.value = `Error: ${error.message}`;
}
</script>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}
.app {
  display: flex;
  flex-direction: column;
  height: 100vh;
  overflow: hidden;
  background: #f8fafc;
}
.header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 16px;
  background: #fff;
  border-bottom: 1px solid #e2e8f0;
}
.title {
  font-size: 14px;
  font-weight: 600;
  color: #0f172a;
  margin-right: auto;
}
.btn {
  padding: 6px 12px;
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 500;
  color: #334155;
}
.btn:hover {
  background: #f1f5f9;
}
.btn-primary {
  background: #0f172a;
  color: #fff;
  border-color: #0f172a;
}
.btn-primary:hover {
  background: #1e293b;
}
.file-input {
  display: none;
}
.status {
  font-size: 12px;
  color: #64748b;
  padding: 4px 8px;
  background: #f1f5f9;
  border-radius: 4px;
}
.main {
  flex: 1;
  display: flex;
  overflow: hidden;
}
</style>

// examples/plugins/docxtemplater/src/App.tsx
import React, { useState, useRef, useCallback } from 'react';
import { DocxEditor, type DocxEditorRef } from '@xcrong/docx-editor-react';
import { PluginHost, templatePlugin } from '@xcrong/docx-editor-react/plugin-api';
import { createEmptyDocument, type Document } from '@xcrong/docx-editor-core';

function createTemplateDocument(): Document {
  const doc = createEmptyDocument();
  const body = doc.package.document;

  if (body.content.length > 0 && body.content[0].type === 'paragraph') {
    body.content[0].content = [
      {
        type: 'run',
        content: [{ type: 'text', text: 'Dear {name},' }],
      },
    ];
  }

  body.content.push(
    { type: 'paragraph', content: [], formatting: {} },
    {
      type: 'paragraph',
      content: [
        {
          type: 'run',
          content: [{ type: 'text', text: 'Thank you for your order. Here are your items:' }],
        },
      ],
      formatting: {},
    },
    { type: 'paragraph', content: [], formatting: {} },
    {
      type: 'paragraph',
      content: [{ type: 'run', content: [{ type: 'text', text: '{#items}' }] }],
      formatting: {},
    },
    {
      type: 'paragraph',
      content: [
        {
          type: 'run',
          content: [
            { type: 'text', text: '  \u2022 {items.name} - ${items.price} x {items.quantity}' },
          ],
        },
      ],
      formatting: {},
    },
    {
      type: 'paragraph',
      content: [{ type: 'run', content: [{ type: 'text', text: '{/items}' }] }],
      formatting: {},
    },
    { type: 'paragraph', content: [], formatting: {} },
    {
      type: 'paragraph',
      content: [{ type: 'run', content: [{ type: 'text', text: '{#hasDiscount}' }] }],
      formatting: {},
    },
    {
      type: 'paragraph',
      content: [
        {
          type: 'run',
          content: [{ type: 'text', text: 'Discount applied: {discountPercent}%' }],
        },
      ],
      formatting: {},
    },
    {
      type: 'paragraph',
      content: [{ type: 'run', content: [{ type: 'text', text: '{/hasDiscount}' }] }],
      formatting: {},
    },
    { type: 'paragraph', content: [], formatting: {} },
    {
      type: 'paragraph',
      content: [{ type: 'run', content: [{ type: 'text', text: 'Total: ${total}' }] }],
      formatting: {},
    },
    { type: 'paragraph', content: [], formatting: {} },
    {
      type: 'paragraph',
      content: [{ type: 'run', content: [{ type: 'text', text: 'Best regards,' }] }],
      formatting: {},
    },
    {
      type: 'paragraph',
      content: [{ type: 'run', content: [{ type: 'text', text: '{company.name}' }] }],
      formatting: {},
    }
  );

  return doc;
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    overflow: 'hidden',
    background: '#f8fafc',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 20px',
    background: '#fff',
    borderBottom: '1px solid #e2e8f0',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flex: 1,
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  title: {
    fontSize: '16px',
    fontWeight: 600,
    margin: 0,
    color: '#0f172a',
    letterSpacing: '-0.025em',
    whiteSpace: 'nowrap',
  },
  titleLink: {
    textDecoration: 'none',
    color: 'inherit',
  },
  badge: {
    fontSize: '11px',
    color: '#fff',
    padding: '3px 8px',
    background: '#3b82f6',
    borderRadius: '4px',
    fontWeight: 500,
  },
  fileName: {
    fontSize: '13px',
    color: '#64748b',
    padding: '4px 10px',
    background: '#f1f5f9',
    borderRadius: '6px',
  },
  fileInputLabel: {
    padding: '8px 14px',
    background: '#0f172a',
    color: '#fff',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    transition: 'background 0.15s',
  },
  fileInputHidden: {
    display: 'none',
  },
  button: {
    padding: '8px 14px',
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    color: '#334155',
    transition: 'all 0.15s',
  },
  newButton: {
    padding: '8px 14px',
    background: '#f1f5f9',
    color: '#334155',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    transition: 'all 0.15s',
  },
  status: {
    fontSize: '12px',
    color: '#64748b',
    padding: '4px 8px',
    background: '#f1f5f9',
    borderRadius: '4px',
  },
  main: {
    flex: 1,
    display: 'flex',
    overflow: 'hidden',
  },
};

export function App() {
  const editorRef = useRef<DocxEditorRef>(null);
  const [currentDocument, setCurrentDocument] = useState<Document | null>(() =>
    createTemplateDocument()
  );
  const [documentBuffer, setDocumentBuffer] = useState<ArrayBuffer | null>(null);
  const [fileName, setFileName] = useState<string>('template.docx');
  const [status, setStatus] = useState<string>('');

  const handleNewDocument = useCallback(() => {
    setCurrentDocument(createTemplateDocument());
    setDocumentBuffer(null);
    setFileName('template.docx');
    setStatus('');
  }, []);

  const handleFileSelect = useCallback(async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      setStatus('Loading...');
      const buffer = await file.arrayBuffer();
      setCurrentDocument(null);
      setDocumentBuffer(buffer);
      setFileName(file.name);
      setStatus('');
    } catch {
      setStatus('Error loading file');
    }
  }, []);

  const handleSave = useCallback(async () => {
    if (!editorRef.current) return;

    try {
      setStatus('Saving...');
      const buffer = await editorRef.current.save();
      if (buffer) {
        const blob = new Blob([buffer], {
          type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = fileName || 'document.docx';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        setStatus('Saved!');
        setTimeout(() => setStatus(''), 2000);
      }
    } catch {
      setStatus('Save failed');
    }
  }, [fileName]);

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <div style={styles.headerLeft}>
          <a
            href="https://github.com/xcrong/docx-editor"
            target="_blank"
            rel="noopener noreferrer"
            style={styles.titleLink}
          >
            <h1 style={styles.title}>@xcrong/docx-editor-react</h1>
          </a>
          <span style={styles.badge}>Docxtemplater Plugin</span>
          {fileName && <span style={styles.fileName}>{fileName}</span>}
        </div>
        <div style={styles.headerRight}>
          <label style={styles.fileInputLabel}>
            <input
              type="file"
              accept=".docx"
              onChange={handleFileSelect}
              style={styles.fileInputHidden}
            />
            Open DOCX
          </label>
          <button style={styles.newButton} onClick={handleNewDocument}>
            New Template
          </button>
          <button style={styles.button} onClick={handleSave}>
            Save
          </button>
          {status && <span style={styles.status}>{status}</span>}
        </div>
      </header>

      <main style={styles.main}>
        <PluginHost plugins={[templatePlugin]}>
          <DocxEditor
            ref={editorRef}
            document={documentBuffer ? undefined : currentDocument}
            documentBuffer={documentBuffer}
            onChange={() => {}}
            onError={(error: Error) => {
              console.error('Editor error:', error);
              setStatus(`Error: ${error.message}`);
            }}
            onFontsLoaded={() => console.log('Fonts loaded')}
            showToolbar={true}
            showRuler={true}
            showZoomControl={true}
            initialZoom={1.0}
          />
        </PluginHost>
      </main>
    </div>
  );
}
